export const jobPositions = [
  {
    _id: "job1",
    title: "Software Engineer",
    companyId: "company1",
    company: "Google",
    level: "mid",
    department: "Engineering",
    location: "Mountain View, CA",
    remote: true,
    salaryRange: { min: 120_000, max: 180_000, currency: "USD" },
    description:
      "Develop and maintain scalable web applications using modern technologies.",
    requirements: ["JavaScript", "Python", "React", "Node.js"],
    postedDate: "2 days ago",
  },
  {
    _id: "job2",
    title: "Product Manager",
    companyId: "company2",
    company: "Microsoft",
    level: "senior",
    department: "Product",
    location: "Seattle, WA",
    remote: false,
    salaryRange: { min: 140_000, max: 200_000, currency: "USD" },
    description:
      "Lead product strategy and execution for enterprise software solutions.",
    requirements: ["Product Strategy", "Agile", "Analytics", "Leadership"],
    postedDate: "1 week ago",
  },
  {
    _id: "job3",
    title: "Data Scientist",
    companyId: "company3",
    company: "Meta",
    level: "mid",
    department: "Data Science",
    location: "Menlo Park, CA",
    remote: true,
    salaryRange: { min: 130_000, max: 190_000, currency: "USD" },
    description:
      "Analyze large datasets to extract insights and build machine learning models.",
    requirements: ["Python", "Machine Learning", "Statistics", "SQL"],
    postedDate: "3 days ago",
  },
  {
    _id: "job4",
    title: "Frontend Developer",
    companyId: "company4",
    company: "Apple",
    level: "entry",
    department: "Engineering",
    location: "Cupertino, CA",
    remote: false,
    salaryRange: { min: 100_000, max: 150_000, currency: "USD" },
    description:
      "Build beautiful and intuitive user interfaces for Apple products.",
    requirements: ["React", "TypeScript", "CSS", "iOS"],
    postedDate: "5 days ago",
  },
  {
    _id: "job5",
    title: "Cloud Engineer",
    companyId: "company5",
    company: "Amazon",
    level: "senior",
    department: "Engineering",
    location: "Seattle, WA",
    remote: true,
    salaryRange: { min: 150_000, max: 220_000, currency: "USD" },
    description: "Design and implement cloud infrastructure solutions on AWS.",
    requirements: ["AWS", "Docker", "Kubernetes", "Terraform"],
    postedDate: "1 day ago",
  },
  {
    _id: "job6",
    title: "UX Designer",
    companyId: "company6",
    company: "Netflix",
    level: "mid",
    department: "Design",
    location: "Los Gatos, CA",
    remote: true,
    salaryRange: { min: 110_000, max: 160_000, currency: "USD" },
    description: "Create user-centered designs for streaming experiences.",
    requirements: ["Figma", "User Research", "Prototyping", "Design Systems"],
    postedDate: "4 days ago",
  },
];
